export const GET_ALL_AUTHOR_REQUEST = 'GET_ALL_AUTHOR_REQUEST';
export const GET_ALL_AUTHOR_SUCCESS = 'GET_ALL_AUTHOR_SUCCESS';
export const GET_ALL_AUTHOR_FAILURE = 'GET_ALL_AUTHOR_FAILURE';

export const GET_AUTHOR_DETAILS_REQUEST = 'GET_AUTHOR_DETAILS_REQUEST';
export const GET_AUTHOR_DETAILS_SUCCESS = 'GET_AUTHOR_DETAILS_SUCCESS';
export const GET_AUTHOR_DETAILS_FAILURE = 'GET_AUTHOR_DETAILS_FAILURE';
