export const GET_ALL_AUTHOR_REQUEST = 'GET_ALL_AUTHOR_REQUEST';
export const GET_ALL_AUTHOR_SUCCESS = 'GET_ALL_AUTHOR_SUCCESS';
export const GET_ALL_AUTHOR_FAILURE = 'GET_ALL_AUTHOR_FAILURE';

export const GET_AUTHOR_DETAILS_REQUEST = 'GET_AUTHOR_DETAILS_REQUEST';
export const GET_AUTHOR_DETAILS_SUCCESS = 'GET_AUTHOR_DETAILS_SUCCESS';
export const GET_AUTHOR_DETAILS_FAILURE = 'GET_AUTHOR_DETAILS_FAILURE';
export const CLEAR_GET_AUTHOR_DETAILS_ERROR = 'CLEAR_GET_AUTHOR_DETAILS_ERROR';

export const ADD_AUTHOR_REQUEST = 'ADD_AUTHOR_REQUEST';
export const ADD_AUTHOR_SUCCESS = 'ADD_AUTHOR_SUCCESS';
export const ADD_AUTHOR_FAILURE = 'ADD_AUTHOR_FAILURE';
export const RESET_ADD_AUTHOR = 'RESET_ADD_AUTHOR';
export const CLEAR_ADD_AUTHOR_ERROR = 'CLEAR_ADD_AUTHOR_ERROR';

export const DELETE_AUTHOR_REQUEST = 'DELETE_AUTHOR_REQUEST';
export const DELETE_AUTHOR_SUCCESS = 'DELETE_AUTHOR_SUCCESS';
export const DELETE_AUTHOR_FAILURE = 'DELETE_AUTHOR_FAILURE';
export const RESET_DELETE_AUTHOR = 'RESET_DELETE_AUTHOR';
export const CLEAR_DELETE_AUTHOR_ERROR = 'CLEAR_DELETE_AUTHOR_ERROR';
