export const GET_ALL_BOOK_REQUEST = 'GET_ALL_BOOK_REQUEST';
export const GET_ALL_BOOK_SUCCESS = 'GET_ALL_BOOK_SUCCESS';
export const GET_ALL_BOOK_FAILURE = 'GET_ALL_BOOK_FAILURE';
export const CLEAR_GET_ALL_BOOK_ERROR = 'CLEAR_GET_ALL_BOOK_ERROR';

export const SEARCH_ALL_BOOKS_REQUEST = 'SEARCH_ALL_BOOKS_REQUEST';
export const SEARCH_ALL_BOOKS_SUCCESS = 'SEARCH_ALL_BOOKS_SUCCESS';
export const SEARCH_ALL_BOOKS_FAILURE = 'SEARCH_ALL_BOOKS_FAILURE';
export const CLEAR_SEARCH_ALL_BOOKS_ERROR = 'CLEAR_SEARCH_ALL_BOOKS_ERROR';

export const GET_BOOK_DETAILS_REQUEST = 'GET_BOOK_DETAILS_REQUEST';
export const GET_BOOK_DETAILS_SUCCESS = 'GET_BOOK_DETAILS_SUCCESS';
export const GET_BOOK_DETAILS_FAILURE = 'GET_BOOK_DETAILS_FAILURE';
export const CLEAR_GET_BOOK_DETAILS_ERROR = 'CLEAR_GET_BOOK_DETAILS_ERROR';

export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';
export const RESET_ADD_BOOK = 'RESET_ADD_BOOK';
export const CLEAR_ADD_BOOK_ERROR = 'CLEAR_ADD_BOOK_ERROR';

export const EDIT_BOOK_REQUEST = 'EDIT_BOOK_REQUEST';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export const EDIT_BOOK_FAILURE = 'EDIT_BOOK_FAILURE';
export const RESET_EDIT_BOOK = 'RESET_EDIT_BOOK';
export const CLEAR_EDIT_BOOK_ERROR = 'CLEAR_EDIT_BOOK_ERROR';

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const RESET_DELETE_BOOK = 'RESET_DELETE_BOOK';
export const CLEAR_DELETE_BOOK_ERROR = 'CLEAR_DELETE_BOOK_ERROR';
