export const GET_ALL_BORROWS_REQUEST = 'GET_ALL_BORROWS_REQUEST';
export const GET_ALL_BORROWS_SUCCESS = 'GET_ALL_BORROWS_SUCCESS';
export const GET_ALL_BORROWS_FAILURE = 'GET_ALL_BORROWS_FAILURE';
export const CLEAR_GET_ALL_BORROWS_ERROR = 'CLEAR_GET_ALL_BORROWS_ERROR';

export const BORROW_BOOKS_REQUEST = 'BORROW_BOOKS_REQUEST';
export const BORROW_BOOKS_SUCCESS = 'BORROW_BOOKS_SUCCESS';
export const BORROW_BOOKS_FAILURE = 'BORROW_BOOKS_FAILURE';
export const RESET_BORROW_BOOKS = 'RESET_BORROW_BOOKS';
export const CLEAR_BORROW_BOOKS_ERROR = 'CLEAR_BORROW_BOOKS_ERROR';

export const RETURN_BOOK_REQUEST = 'RETURN_BOOK_REQUEST';
export const RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS';
export const RETURN_BOOK_FAILURE = 'RETURN_BOOK_FAILURE';
export const RESET_RETURN_BOOK = 'RESET_RETURN_BOOK';
export const CLEAR_RETURN_BOOK_ERROR = 'CLEAR_RETURN_BOOK_ERROR';
