export const GET_ALL_LOAN_REQUEST = 'GET_ALL_LOAN_REQUEST';
export const GET_ALL_LOAN_SUCCESS = 'GET_ALL_LOAN_SUCCESS';
export const GET_ALL_LOAN_FAILURE = 'GET_ALL_LOAN_FAILURE';
export const CLEAR_GET_ALL_LOAN_ERROR = 'CLEAR_GET_ALL_LOAN_ERROR';

export const LOAN_REQUEST = 'LOAN_REQUEST';
export const LOAN_SUCCESS = 'LOAN_SUCCESS';
export const LOAN_FAILURE = 'LOAN_FAILURE';
export const RESET_LOAN = 'RESET_LOAN';
export const CLEAR_LOAN_ERROR = 'CLEAR_LOAN_ERROR';

export const RETURN_REQUEST = 'RETURN_REQUEST';
export const RETURN_SUCCESS = 'RETURN_SUCCESS';
export const RETURN_FAILURE = 'RETURN_FAILURE';
export const RESET_RETURN = 'RESET_RETURN';
export const CLEAR_RETURN_ERROR = 'CLEAR_RETURN_ERROR';
